### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by oblank** [fmsouza/ethereum-wallet#1]
```
error: bundling failed: Error: Unable to resolve module `@common/utils/shims` from `/codes/react-native/EthereumWallet/index.js`: Module does not exist in the module map

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset Metro Bundler cache: `rm -rf $TMPDIR/react-*` or `npm start -- --reset-cache`.  4. Remove haste cache: `rm -rf $TMPDIR/haste-map-react-native-packager-*`.
    at ModuleResolver.resolveDependency (/codes/react-native/EthereumWallet/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:311:1719)
    at ResolutionRequest.resolveDependency (/codes/react-native/EthereumWallet/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:96:16)
    at DependencyGraph.resolveDependency (/codes/react-native/EthereumWallet/node_modules/metro/src/node-haste/DependencyGraph.js:269:4352)
    at dependencies.map.relativePath (/codes/react-native/EthereumWallet/node_modules/metro/src/DeltaBundler/traverseDependencies.js:337:19)
    at Array.map (<anonymous>)
    at resolveDependencies (/codes/react-native/EthereumWallet/node_modules/metro/src/DeltaBundler/traverseDependencies.js:336:16)
    at /codes/react-native/EthereumWallet/node_modules/metro/src/DeltaBundler/traverseDependencies.js:128:33
    at Generator.next (<anonymous>)
    at step (/codes/react-native/EthereumWallet/node_modules/metro/src/DeltaBundler/traverseDependencies.js:256:306)
    at /codes/react-native/EthereumWallet/node_modules/metro/src/DeltaBundler/traverseDependencies.js:256:466
 BUNDLE  [ios, dev] ./index.js ░░░░░░░░░░░░░░░░ 0.0% (0/1), failed.

```

run `watchman watch-del-all` and `rm -rf node_modules && npm install` not worked 

env 
```
react-native-cli: 2.0.1
react-native: 0.54.0
```

node:
```
v8.9.4
```

**Comment by fmsouza** [comment]
@oblank Is your local copy of the code up-to-date with the latest `master` branch state?

**Comment by fmsouza** [comment]
I'll leave this closed for now. If you still have this error after updating your copy come back here and we can keep discussing this issue.
