### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by yuppieghost** [fmsouza/ethereum-wallet#8]
bundling failed: Error: Unable to resolve module `../../../node_modules/react-native/src/common/utils` from `/home/cpc/WebstormProjects/ethereum-wallet/src/common/stores/wallet.js`: The module `../../../node_modules/react-native/src/common/utils` could not be found from `/home/cpc/WebstormProjects/ethereum-wallet/src/common/stores/wallet.js`. Indeed, none of these files exist:
  * `/home/cpc/WebstormProjects/ethereum-wallet/node_modules/react-native/src/common/utils(.native||.android.js|.native.js|.js|.android.json|.native.json|.json)`
  * `/home/cpc/WebstormProjects/ethereum-wallet/node_modules/react-native/src/common/utils/index(.native||.android.js|.native.js|.js|.android.json|.native.json|.json)`
    at ModuleResolver.resolveDependency (/home/cpc/WebstormProjects/ethereum-wallet/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:167:697)
    at ResolutionRequest.resolveDependency (/home/cpc/WebstormProjects/ethereum-wallet/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:80:16)
    at DependencyGraph.resolveDependency (/home/cpc/WebstormProjects/ethereum-wallet/node_modules/metro/src/node-haste/DependencyGraph.js:237:485)
    at Object.resolve (/home/cpc/WebstormProjects/ethereum-wallet/node_modules/metro/src/lib/transformHelpers.js:116:25)
    at dependencies.map.result (/home/cpc/WebstormProjects/ethereum-wallet/node_modules/metro/src/DeltaBundler/traverseDependencies.js:298:29)
    at Array.map (<anonymous>)
    at resolveDependencies (/home/cpc/WebstormProjects/ethereum-wallet/node_modules/metro/src/DeltaBundler/traverseDependencies.js:294:16)
    at /home/cpc/WebstormProjects/ethereum-wallet/node_modules/metro/src/DeltaBundler/traverseDependencies.js:159:33
    at Generator.next (<anonymous>)
    at step (/home/cpc/WebstormProjects/ethereum-wallet/node_modules/metro/src/DeltaBundler/traverseDependencies.js:239:307)

After npm start ,I exec react-native run-android ,then I got this error, what should I do now?

**Comment by fmsouza** [comment]
The project is updated nwo and the build issues were resolved.
